### ISSUE TITLE
Content and Map of this Source is not available (only size() is supported) webpack5

### ISSUE THREAD

**Issue by AnubhutiRoX** [webpack/webpack-sources#113]
![Issue](https://user-images.githubusercontent.com/18062708/125255758-6437d400-e319-11eb-9b8e-73c3d2e7ef0f.PNG)
After upgrading webpack from 4 to 5 and webpack-sources - 2.3.0, I am facing this issue. 

Found one similar issue - https://github.com/GoogleChromeLabs/size-plugin/issues/40 but mine is coming from write-file-webpack-plugin, version 4.5.1

**Comment by alexander-akait** [comment]
Bug in https://github.com/GoogleChromeLabs/size-plugin/issues/40, please wait the fix
