### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Superoryco** [webpack/webpack-sources#122]
Somehow the 'checkOriginalContent' function in [ReplaceSource.js](https://github.com/webpack/webpack-sources/blob/5024ff8d42c97b24a32f60b4d0cffa2b5c3a49dd/lib/ReplaceSource.js#L159) failed due to null value from sourceContents[sourceIndex], need a fix maybe.

**Comment by Superoryco** [comment]
#121

**Comment by modestfake** [comment]
First I got the the error in `ReplaceSource.js`. I applied the same fix as in the PR #121, it helped but then I also get similar error but in a different place
![image](https://user-images.githubusercontent.com/16977959/127389376-1a280215-c72e-4c4f-ab3c-b153cee9a832.png)

Seems like it's the same stack trace as in https://github.com/webpack/webpack/issues/13879

**Comment by Superoryco** [comment]
@modestfake I've not seen this problem yet in my project, try [this](https://github.com/webpack/webpack-sources/pull/121/commits/2138fd4d1f586a963ad85d6ba5d905f6d4c2fb68) maybe?

**Comment by modestfake** [comment]
@Superoryco yes, this worked! Thanks for the fix! Hopefully it will be released soon.

**Comment by Superoryco** [comment]
@sokra Report: Exception still exists in 3.0.4, but from a different place:
[at checkOriginalContent (.../node_modules/webpack-sources/lib/ReplaceSource.js:169:40)](https://github.com/webpack/webpack-sources/blob/d103b21f883de762132cb665d8444904185ebae3/lib/ReplaceSource.js#L169)

**Comment by Superoryco** [comment]
Fixed by [d103b21](https://github.com/webpack/webpack-sources/commit/d103b21f883de762132cb665d8444904185ebae3), if still happened, delete node_modules folder and .lock file, then a fresh install.
