### ISSUE TITLE
I wan replace some string in the code

### ISSUE THREAD

**Issue by denglingbo** [webpack/webpack-sources#14]
code: xx.js
source: abcdedfg, ../images/xx.png ....

i want replace the '../images/xx.png' to 'images/xx.png'

compilation.assets[file] = new ReplaceSource(
    newCode
)

npm run build:
/node_modules/webpack-sources/lib/ReplaceSource.js:35
	return this._replaceString(this._source.source());
	                                        
TypeError: this._source.source is not a function

**Comment by sokra** [comment]
ReplaceSource takes a `Source` as argument. i. e. use a `RawSource` or an `OriginalSource`.
