### ISSUE TITLE
Destructuring not mapped correctly

### ISSUE THREAD

**Issue by Vanuan** [webpack/webpack-sources#15]
Here's an example
```
  function destructuringNotWorking(obj) {
    const { prop1, prop2 } = this.obj; // <-- can't set breakpoint here
    console.log(prop1);
  }
  destructuringNotWorking.apply({obj: { prop1: 1, prop2: 2} });

```

You can clone it here: https://github.com/Vanuan/webpack-demo-app/commit/d2b1fb74e2468678534a8a71a9163e703ad7364f

**Comment by Vanuan** [comment]
Here's visualization using http://paulirish.github.io/source-map-visualization/#custom
![screenshot from 2017-04-03 00 57 20](https://cloud.githubusercontent.com/assets/361985/24591390/d73e109e-1808-11e7-8413-5df45a204c92.png)

**Comment by Vanuan** [comment]
This doesn't look right
![screenshot from 2017-04-03 01 01 03](https://cloud.githubusercontent.com/assets/361985/24591405/29afc00c-1809-11e7-8806-b4b0f0b4277a.png)

**Comment by sokra** [comment]
This is not in the scope of this lib. You should file an issue on your transpiler (babel).
