### ISSUE TITLE
Harmony imports are not mapped

### ISSUE THREAD

**Issue by Vanuan** [webpack/webpack-sources#16]
You can't set a breakpoint to the import line. Only `require` works.

![screenshot from 2017-04-03 01 07 20](https://cloud.githubusercontent.com/assets/361985/24591457/36d380d8-180a-11e7-9497-e40806151edf.png)

**Comment by sokra** [comment]
`import` is not a statement, it's a declaration. You can't set breakpoints on declarations.

The spec says before starting to evaluate the source code all imports have to be resolved.
