### ISSUE TITLE
Sources whose source() return strings do not have the correct size() if it contains unicode

### ISSUE THREAD

**Issue by mzgoddard** [webpack/webpack-sources#18]
Strings returned by `source()` that have unicode characters outside of the ascii range have lengths that are not the number of bytes of the string but the number of unicode characters in the string. The number of bytes could be computer by casting the string to a `Buffer` whose length will be the number of bytes or other possible ways.

As it is, webpack features and plugins that depend on an accurate size value to produce some output or reflect some information are likely to not work as expected.

**Comment by evilebottnawi** [comment]
@mzgoddard problem still exists? IF yes, can you provide minimum reproducible test repo?
