### ISSUE TITLE
Improve Code Coverage

### ISSUE THREAD

**Issue by gnarf** [webpack/webpack-sources#2]
I was noticing that the code coverage here is very low (<60%)

**Comment by gnarf** [comment]
ugh, hit tab,enter accidentally too soon...

https://codecov.io/gh/webpack/webpack-sources/

I was wondering if this is something you'd like some help improving, and in that vein is there any bits of this code that I should avoid covering because it might get removed?

**Comment by sokra** [comment]
Everything in this repo is relevant.

I really appreciate your help here. The test infrastructure is already there, so just send a PR with tests and I'll merge it. Thanks 👍

**Comment by TheLarkInn** [comment]
@gnarf I've also got a branch for upgrading the library to ES6. If this is something that interests you as well you can PR against that branch and just @ mention me so I can merge it as well. I could use help ensuring that deps are ES6 friendly and that we can use the correct module and exports.

**Comment by gnarf** [comment]
That sounds like a plan! :)

I'm super busy this week myself, but I'll come back around to this soon!

**Comment by sokra** [comment]
fixed
