### ISSUE TITLE
Improve performance of `node` method in `ReplaceSources`

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack-sources#29]
This is related to this issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/161

I have a huge code base with thousands of files, and after several hours of trying to figure out with uglify-js was slow when enabling sourcemaps.  I ended up looking into this library and it's source.

I noticed that `node` method in `ReplaceSources` takes a lot of time to execute, infact if I disable `columns` from `map()` the it improves the speed by at least 40 minutes.

https://github.com/webpack/webpack-sources/blob/master/lib/ReplaceSource.js#L68

**Comment by alan-agius4** [comment]
@sokra, any feedback please?

**Comment by yshterev** [comment]
@alan-agius4 Hi.. any workaround for this issue?

**Comment by alan-agius4** [comment]
There is this PR
https://github.com/webpack/webpack-sources/pull/23 but we are still waiting
for it to be merged.

**Comment by edmorley** [comment]
#23 has now been merged/released, so this issue can be closed :-)
