### ISSUE TITLE
remove unnecessary memory allocation from ConcatSource and ReplaceSource

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack-sources#30]
The code in `ConcatSource::source()` and `ReplaceSource::_replaceString()` is using `array.join("")` which causes allocation of new strings. Using simple concatenation with += instead causes node to create what it calls something like "concatenated strings" internally which reuse the memory of the original strings being concatenated (this is probably possible since strings are immutable).

This problem was discovered by recording a "memory allocation profile" using chrome dev tools for the duration of the whole webpack build.

Before:
![image](https://user-images.githubusercontent.com/95201/33223574-93450976-d115-11e7-89f7-5e63f354ab1a.png)

After change:
![image](https://user-images.githubusercontent.com/95201/33223954-b43bee02-d119-11e7-8213-9a53757d7904.png)

**Comment by MagicDuck** [comment]
I will create a PR soon.

**Comment by filipesilva** [comment]
Think this can be closed since https://github.com/webpack/webpack-sources/pull/31 was merged.

**Comment by d3viant0ne** [comment]
Thanks @MagicDuck

**Comment by MagicDuck** [comment]
No worries :)
There's a bunch more, on a more minor level, that i have seen in the source-list-map project. I want to see what can be done. The most bizarre one is this: https://github.com/webpack/source-list-map/blob/master/lib/helpers.js 
I am not sure why dev tools is reporting getNumberOfLines as allocating tens of mb in my case...
