### ISSUE TITLE
Refactor: Convert the existing code to Idiomatic ES6

### ISSUE THREAD

**Issue by abiduzz420** [webpack/webpack-sources#35]
I would like to refactor the code base wherever possible so that we are using the latest ES6 syntax.
One example from the source would be:
Turning this
```
if(source.node) this.node = function(options) {
			return this._source.node(options);
		};
```
into
```
if(source.node) this.node = (options) => this._source.node(options);
```
This sort of code would decrease verbosity and helps contributors to write efficient and better code. At some places, I will be using [Lebab](https://github.com/lebab/lebab), a codemod for changing ES5 to ES6 code. Would like to know your thoughts.

**Comment by evilebottnawi** [comment]
@abiduzz420 feel free to send PR

**Comment by sokra** [comment]
done
