### ISSUE TITLE
Should add `pop` public method for `ConcactSource` ?

### ISSUE THREAD

**Issue by lamhieu-vk** [webpack/webpack-sources#50]
Some Webpack plugins use `ConcactSource` to add source map URL and sometimes we should remove or pop item from `ConcactSource`, Is there any more reason for us to do it? I can help if this is agreed.

**Comment by evilebottnawi** [comment]
What do you mean, please clarify

**Comment by lamhieu-vk** [comment]
@evilebottnawi because I see `ConcactSource` have children is an array, when I want to remove an item from list but a must-do manual. If we support add method I think we support remove method too.

**Comment by evilebottnawi** [comment]
@lamhieu-vk can you provide example of code, thanks

**Comment by lamhieu-vk** [comment]
@evilebottnawi for example, in plugin A do something and set assets is a `ConcactSource ` have children like
```js
const asset = ConcactSource {
  children: [
    'code1 - is a header comment', 
    'code2', 
    'code3 - is a source map',
  ],
}
```
in my plugin, I want to have a way to remove children in `ConcactSource` from plugin A return, for example:
```js
 // remove comment header
asset.remove(0);

// or remove source map
asset.remove(2);
```

**Comment by lamhieu-vk** [comment]
@sokra can you tell me anything?

**Comment by sokra** [comment]
`ConcatSource` optimizes children internally after adding items. So `removing` might sometimes won't work as expected.

Anyway `Source`s are intended to be immutable after initial generation. `remove` doesn't fit good into the design.

Avoid adding items at first place. You can use an array to construct the items and add them to the `ConcatSource` after done.
