### ISSUE TITLE
Expand Webpack's benchmark tests to measure webpack-sources perf

### ISSUE THREAD

**Issue by hccampos** [webpack/webpack-sources#7]
Since there is now a benchmarking test suite for `webpack`, I think it would be useful to be able to measure performance improvements in `webpack-sources` too. Since it is a separate package I think changes to `webpack-sources` will affect all the measurements in the main benchmark and it will therefore not show any performance differences.

For huge bundles, `webpack-sources` has to do a lot of work and any improvements here will most likely strongly impact the performance of `webpack` in general.

**Comment by evilebottnawi** [comment]
@hccampos do you interested in PR?

**Comment by sokra** [comment]
https://webpack.github.io/benchmark/
