### ISSUE TITLE
How to replace the RawSource's value ? 

### ISSUE THREAD

**Issue by zhanyuzhang** [webpack/webpack-sources#82]
I wtite a webpack plugin to compress image. For example  there is an img's rawSource instance:
```
RawSource {
  _value:
   <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 65 00 00 00 de 08 06 00 00 00 24 71 ce 79 00 00 20 00 49 44 41 54 78 9c ed bd 07 98 1c d5 95 ... >,
  existsAt:
   'E:\\git\\tinyimg-webpack-plugin\\test\\dist\\images\\logo.d8d2.png',
  emitted: true }
```

After compressing the img  , I want to repalce the the origin img by new img:
```
myRawSource._value = 'new img binary content';
```
but, it doesn't work.

I have to use fs.writeFile() to  make it work as follows:
```
fs.wirteFile(myRawSource.existsAt, 'new img binary content', 'binary');
```

Can any body tell me whether there is a better solution ?

**Comment by evilebottnawi** [comment]
You should not replace content, just create new instance, example of compression plugin https://github.com/itgalaxy/imagemin-webpack/blob/master/src/ImageminPlugin.js
