### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap (reproducible)

### ISSUE THREAD

**Issue by dlong500** [webpack/webpack-sources#89]
@evilebottnawi Ok, I've finally created a reproducible test repo (as requested in #55).  I forked HashemKhalifa/webpack-react-boilerplate and the ONLY things I changed were:
-  upgrading to webpack@5 RC
-  setting babel preset-env to use `targets: 'defaults'`

Here is the repo: https://github.com/dlong500/webpack-react-boilerplate/tree/source-map-diag
The changes are in the source-map-diag branch.

Building the project via `yarn run build` (or npm) yields the following:
![source-map-diag](https://user-images.githubusercontent.com/430481/94032351-e60c4000-fd8d-11ea-8815-770c2676b420.png)

**Comment by evilebottnawi** [comment]
Just note, please migrate from `optimize-css-assets-webpack-plugin`  to https://github.com/webpack-contrib/css-minimizer-webpack-plugin

**Comment by evilebottnawi** [comment]
Someone generates a bad source map

**Comment by rob-baker-ar** [comment]
If it's any help, this repo (from https://github.com/webpack/webpack/issues/11517) is a more minimal way of reproducing the bug:

https://github.com/rob-baker-ar/webpack-issue

**Comment by chaffeqa** [comment]
oh wow thanks @rob-baker-ar ! i jsut created a reproducible version myself:

https://github.com/chaffeqa/webpack-5-sourcemaps-repro

```
yarn install
yarn build
```
