### ISSUE TITLE
HookWebpackError: item.node is not a function

### ISSUE THREAD

**Issue by vespakoen** [webpack/webpack-sources#92]
I am setting up a new project with the latest and greatest of all tools, and ran into the following situation:

I am using:

`webpack@5.1.0`
`webpack-cli@next`
`wrapper-webpack-plugin@2.1.0`

webpack.config.js
```js
plugins: [
    new WrapperPlugin({
        header: () => fs.readFileSync(path.resolve(__dirname, 'shim.js'), 'utf8'),
    }),
]
```

`terser-webpack-plugin@5.0.0`

webpack.config.js
```js
minimizer: [
    new TerserPlugin({
        terserOptions: {
            compress: {
                collapse_vars: false,
                conditionals: false,
                comparisons: false,
            },
            output: {
                comments: false,
            },
        },
    }),
],
```

(Yarn 2 with `loose` mode enabled)

Now, when I debug the error (has to be on Node 13+, to make it work with Yarn 2's PnP, I used node 14):

package.json
```json
"debug": "node --inspect --inspect-brk=5858 $(yarn bin webpack) --config webpack.config.js"
```

I get this:

<img width="1202" alt="Screenshot 2020-10-15 at 15 59 49" src="https://user-images.githubusercontent.com/876117/96139780-7823e600-0eff-11eb-9972-f17a10983b95.png">

So it looks like the `CachedSource` is missing the `node` function.
The other possibility is that the `CachedSource` is not an allowed child for `ConcatSource`, so i'll move up the call stack to where the children are coming from and end up over here:

<img width="1202" alt="Screenshot 2020-10-15 at 16 02 14" src="https://user-images.githubusercontent.com/876117/96140052-cd5ff780-0eff-11eb-88ff-36d3d61bbd87.png">

I added a breakpoint to indicate the line where the `children` are coming from.

They are coming from webpack's `compilation.getAsset('outfile.js').source`.

The `source` is a ConcatSource, containing 3 children
1. A string with the header coming from the WrapperPlugin
2. The (offending?) `CachedSource`, which contains webpack runtime code under `_source(which is a ConcatSource)._children`
3. An empty string (not sure where this comes from)

I am not sure what is right and what is wrong, so I am asking for a pointer in the right direction.

I'd be glad to send a PR, but I guess I need some help since I am not sure what should happen.

**Comment by evilebottnawi** [comment]
Can you provide reproducible repo? Maybe API used in wrong way

**Comment by vespakoen** [comment]
Sure thing, setting one up right now

**Comment by vespakoen** [comment]
Looks like it might be coming from `wrapper-webpack-plugin` using deprecated API's?

https://github.com/levp/wrapper-webpack-plugin/issues/11

**Comment by evilebottnawi** [comment]
Yes, https://github.com/levp/wrapper-webpack-plugin/blob/master/wrapper-webpack-plugin.js#L53, it can be `Buffer`/`String`

**Comment by evilebottnawi** [comment]
Also here other issue - `webpack-sources@1` doesn't have compatibility with `webpack-sources@2` in some edge cases, but `terser-webpack-plugin@5` supports only `webpack@5` and `webpack-sources@2`

**Comment by vespakoen** [comment]
This seems to be working, but not sure if I did it right, hope it might help to get this fixed:

```js
const webpack = require('webpack')
const ConcatSource = require("webpack-sources").ConcatSource;
const ModuleFilenameHelpers = require("webpack/lib/ModuleFilenameHelpers");

class WrapperPlugin {

	/**
	 * @param {Object} args
	 * @param {string | Function} [args.header]  Text that will be prepended to an output file.
	 * @param {string | Function} [args.footer] Text that will be appended to an output file.
	 * @param {string | RegExp} [args.test] Tested against output file names to check if they should be affected by this
	 * plugin.
	 * @param {boolean} [args.afterOptimizations=false] Indicating whether this plugin should be activated before
	 * (`false`) or after (`true`) the optimization stage. Example use case: Set this to true if you want to avoid
	 * minification from affecting the text added by this plugin.
	 */
	constructor(args) {
		if (typeof args !== 'object') {
			throw new TypeError('Argument "args" must be an object.');
		}

		this.header = args.hasOwnProperty('header') ? args.header : '';
		this.footer = args.hasOwnProperty('footer') ? args.footer : '';
		this.afterOptimizations = args.hasOwnProperty('afterOptimizations') ? !!args.afterOptimizations : false;
		this.test = args.hasOwnProperty('test') ? args.test : '';
	}

	apply(compiler) {
		const header = this.header;
		const footer = this.footer;
		const tester = {test: this.test};

		compiler.hooks.thisCompilation.tap('WrapperPlugin', (compilation) => {
			if (compilation.hooks.processAssets) {
				compilation.hooks.processAssets.tap(
					{
						name: 'WrapperPlugin',
						stage: webpack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONS, 
					},
					(chunks) => wrapChunks(compilation, chunks),
				);
				return;
			}

			compilation.hooks.optimizeChunkModules.tap('WrapperPlugin', (chunks) =>
				wrapChunks(compilation, chunks)
			);
		});

		function wrapFile(compilation, fileName, chunkHash) {
			const headerContent = (typeof header === 'function') ? header(fileName, chunkHash) : header;
			const footerContent = (typeof footer === 'function') ? footer(fileName, chunkHash) : footer;
			const asset = compilation.getAsset(fileName)
			console.log(asset, asset.source.buffer())
			compilation.updateAsset(fileName, new ConcatSource(
				String(headerContent),
				compilation.getAsset(fileName).source.buffer().toString(),
				String(footerContent),
			))
		}

		function wrapChunks(compilation, chunks) {
			Object.keys(chunks).forEach(fileName => {
				const chunk = chunks[fileName]
				const args = {
					hash: compilation.hash,
				};
				if (ModuleFilenameHelpers.matchObject(tester, fileName)) {
					console.log('match')
					wrapFile(compilation, fileName, args);
				}
			})
		}
	}
}


module.exports = {
	entry: path.resolve(__dirname, './index.js'),
	devtool: false,
	mode: 'development',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'bundle.js',
	},
	plugins: [
		new WrapperPlugin({
			header: fs.readFileSync(path.resolve(__dirname, 'shim.js'), 'utf8'),
		}),
	],
	target: 'web',
	optimization: {
		minimize: true,
		minimizer: [
			new TerserPlugin({
				terserOptions: {
					compress: {
						collapse_vars: false,
						conditionals: false,
						comparisons: false,
					},
					output: {
						comments: false,
					},
				},
			}),
		],
	},
}
```

**Comment by evilebottnawi** [comment]
@vespakoen my recommendation to use `compiler.webpack.sources` for webpack@5 instead `require('webpack')`

**Comment by xmsz** [comment]
Any update?

**Comment by evilebottnawi** [comment]
No updates, answer was given, please use `compiler.webpack.sources` and do not use `webpack-sources` directly
