### ISSUE TITLE
webpack-sources' Source type is not assigneable to webpack5 source type

### ISSUE THREAD

**Issue by blackrabbit99** [webpack/webpack-sources#93]
Code sample
```
    const fileAsset = compilation.assets[fileName];
    const source = new ReplaceSource(fileAsset);
```

TS Compilation Error
```
 Argument of type 'Source' is not assignable to parameter of type 'import("<path>/@types/webpack-sources/lib/Source")'.
  The types returned by 'map(...)' are incompatible between these types.
    The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
      Type 'Object' is missing the following properties from type 'RawSourceMap': version, sources, names, mappings, file

52         const source = new ReplaceSource(fileAsset);
```

webpack@5.1.3 Source type
```
declare class Source {
	constructor();
	size(): number;
	map(options: MapOptions): Object;
	sourceAndMap(options: MapOptions): { source: string | Buffer; map: Object };
	updateHash(hash: Hash): void;
	source(): string | Buffer;
	buffer(): Buffer;
}
```

@types/webpack-sources@2.0.0 Source type

```
declare abstract class Source {
    source(): string | ArrayBuffer;
    buffer(): Buffer;
    size(): number;
    map(options?: MapOptions): RawSourceMap | null;
    sourceAndMap(options?: MapOptions): SourceAndMapResult;
    updateHash(hash: Hash): void;
}
```

```
map(options: MapOptions): Object; vs map(options?: MapOptions): RawSourceMap | null;
```

Expectation from my side they should be corresponding to the same type as a part of single ecosystem

**Comment by evilebottnawi** [comment]
Sorry, no, types are different between webpack@4 and webpack@5

**Comment by blackrabbit99** [comment]
From what I got @types/webpack-sources@2.0.0 uses types from webpack 4 so to use it with webpack 5 types should be updated ?

**Comment by evilebottnawi** [comment]
My reccomendation - drop webpack@4 support and migrate on webpack@5 + use types from webpack@5 only

**Comment by blackrabbit99** [comment]
webpack-sources@2.0.0  written in js so to use it with webpack5 I need to be sure webpack-sources typings correspond to webpack5 types but now as I see it isn't

**Comment by evilebottnawi** [comment]
@blackrabbit99 do not use `@types/webpack-sources@2.0.0`

**Comment by blackrabbit99** [comment]
@evilebottnawi maybe I got you wrong but I can not use `webpack-sources` w/o typings because there is no declaration file.
`webpack` consumes `webpack-sources` only in js part so everything work corrects. 

But inside plugins written on TS webpack-sources could not be used safety because of types inconsistency.
Any plans about types synchronisation ?

**Comment by blackrabbit99** [comment]
`webpack` has self defined declaration for `webpack-sources` does it make sence to handle this typing on `webpack-source` package level so this types will become the source of truth for consumers of this library

Alternatives are following:
* trust to `@types/webpacks-sources`
* declare own typings for `webpacks-sources` on plugin level 

Both of them are not safe enough as for me.

So this issue make plugin creation using TS really not perfect

**Comment by evilebottnawi** [comment]
@blackrabbit99 Why do you need `@types/webpacks-sources`? Don't use `webpack-source` directly, it is invalid

**Comment by blackrabbit99** [comment]
@evilebottnawi got you point. One of my plugins has dependency to `webpacks-sources` and uses `ReplaceSource` from it. Does it mean I can get access to `ReplaceSource` service directly from webpack ?

**Comment by evilebottnawi** [comment]
> Does it mean I can get access to ReplaceSource service directly from webpack ?

Yes, it is right way, no need to ahve this in deps, also it allows to use keep compatibility better between webpack versions

**Comment by TheLarkInn** [comment]
@blackrabbit99 you can even do `import {sources} from 'webpack'` if you need to as well in webpack@5. Closing issue.
