### ISSUE TITLE
[question] why ReplaceSource.map.sourcesContent not change

### ISSUE THREAD

**Issue by yuzhidi** [webpack/webpack-sources#98]
Hi,
    ReplaceSource test case show `expect(resultText).toBe("Hi bye W0000rld!\n{\n Multi Line\n}\nLast Line");` [L49](https://github.com/webpack/webpack-sources/blob/9ec78f2ef3d9169293636c48b7741ebb7b457ac6/test/ReplaceSource.js#L49) result changed
but `resultMap.map.sourcesContent`，`resultListMap.map.sourcesContent` is also the `originalText`.
the print code `console.log("resultMap.map.sourcesContent: ", resultMap.map.sourcesContent);` show
`    console.log
      resultMap.map.sourcesContent:  [ 'Hello World!\n{}\nLine 3\nLine 4\nLine 5\nLast\nLine' ]
`
   Why result changed by sourcesContent not change ?

Thx!

**Comment by evilebottnawi** [comment]
Because it should not change
